#!/usr/bin/env bash
# This is not ideal when you consider this is not for a Virtual Screen only, but eh
xrandr --output Virtual-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal

export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

feh --bg-fill $SCRIPTPATH/background.png
dunst -c $SCRIPTPATH/dunstrc
polybar -c $SCRIPTPATH/polybar.config
